# Site settings
baseurl = "https://threesixtytwo.co/"
languageCode = "en-us"
title = "three|sixtytwo"
theme = "hugo-smpl-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]

# Enter your tracking code to enable Google analytics
googleAnalytics = ""



[params]
  # You can use Markdown for urls [text](//domain.tld/source)
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons.

  # To provide more meta data for search engines feel free to add a few information.
  # This lines will be inserted as meta tags.
  name = "threesixtytwo"
  description = "Digital products done."
  custom_css = ["css/main.css"] #override css
   date_format = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "A digital marketing &amp; design agency"
    subtitle = "We love the Web and the work we do.<br/>We work closely with our clients to deliver the best possible solutions for their needs"

  [params.wrapper]
    enable = true
    title = "About Us"
    italic = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics"
    paragraph = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id"

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "We believe in great ideas"
    content = "Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."
    [params.feature.button]
      caption = "View Works"
      url = "#"

  [params.call]
    enable = true
    title = "We design delightful digital experiences."
    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: contact@mail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"
   #Background
  [params.background]
    image = "images/IMAG0782b.jpg"

    # Enable and set background fade speed
    [params.background.fade]
      enable = true
      speed = 500

  # Logo section
  [params.logo]
    enable = true
    image = "images/362portWhite.png"
    alt = "threesixtytwo.co"
    width = "200"

  # Header section
  [params.header]
    enable = true
    title = "Engineering | Product"

  # Quote section
  [params.quote]
    enable = true
    text = "For thinkers and do'ers, <br />tinkerers and tailors,<br />innovators and changemakers <br />For anyone that believes great products come from great teams.<br /><br />"

  # Social icons section
  # Add a modifier class to increase size
  # fa-lg, fa-2x, fa-3x, fa-4x, fa-5x
  # e.g., icon = "fa-instagram fa-lg"
  [params.social_icons]
    enable = true

  #[[params.social]]
  #  title = "Dribbble"
  #  icon = "fa-dribbble"
  #  link = "http://dribbble.com/CarlosAlvarez"

  #[[params.social]]
  #  title = "Twitter"
  #  icon = "fa-twitter"
  #  link = "http://twitter.com/BlackTie_co"

 # [[params.social]]
 #   title = "Premium Themes"
 #   icon = "fa-briefcase"
 #   link = "https://wrapbootstrap.com/user/Basicoh"

 # [[params.social]]
 #   title = "Free Themes"
 #   icon = "fa-heart"
 #   link = "http://BlackTie.co"

 # [[params.social]]
 #   title = "Blog"
 #   icon = "fa-comment"
 #   link = "http://freelance.postach.io"

  [[params.social]]
    title = "Email Me!"
    icon = "fa-envelope"
    link = "mailto:us@threesixtytwo.co"

  #[[params.social]]
  #  title = "Newsletter"
  #  icon = "fa-coffee"
  #  link = "http://eepurl.com/Eck_T"
